# Generated by Django 2.2.2 on 2019-12-07 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comments', 'verbose_name_plural': 'comments'},
        ),
    ]
