# Generated by Django 2.2.2 on 2019-08-30 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 22, 6, 0, 390526), verbose_name='date published'),
        ),
    ]
